baseurl: /
title: Skribble
languages:
  de:
    languageName: Deutsch
    weight: 2
    contentDir: content/german
    menu:
      main:
        - name: Über uns
          url: /ueber-uns/
          weight: 5
        - name: Identifikation
          url: /identifikation/
          weight: 15
        - name: Kontakt
          url: /kontakt/
          weight: 20
      footer1:
        - name: Identifikation
          url: /identifikation/
          weight: 15
      footer2:
        - name: Über uns
          url: /ueber-uns/
          weight: 5
        - name: Team
          url: /team/
          weight: 10
        - name: Kontakt
          url: /kontakt/
          weight: 20
      footer3:
        - name: Help-Center
          url: https://help.skribble.com/deutsch
          weight: 5
      footer4:
        - name: Datenschutzbestimmungen
          url: /de/datenschutz
          weight: 10
        - name: Impressum
          url: /de/impressum
          weight: 15
    header:
      login:
        label: Login
        href: https://my.skribble.com/login?lang=de
      tryItOut:
        label: Jetzt ausprobieren
        href: https://my.skribble.com/signup?lang=de
    footer:
      navigation:
        titleColumn1: Plattform
        titleColumn2: Über uns
        titleColumn3: Ressourcen
      newsletterTitle: Newsletter
      newsletterText: Elektronische Signaturen und digitales Vertrauen sind brandaktuelle Themen. Bleibe auf dem Laufenden! Siehe unsere <a href="/datenschutz">Datenschutzerklärugen</a>.
  en:
    languageName: English
    weight: 1
    contentDir: content/english
    menu:
      main:
        - name: About
          url: /about/
          weight: 5
        - name: Identification
          url: /identification/
          weight: 15
        - name: Contact
          url: /contact/
          weight: 20
      footer1:
        - name: Identification
          url: /identification/
          weight: 15
      footer2:
        - name: About
          url: /about/
          weight: 5
        - name: Team
          url: /team/
          weight: 10
        - name: Contact
          url: /contact/
          weight: 20
      footer3:
        - name: Help-Center
          url: https://help.skribble.com/english
          weight: 5
      footer4:
        - name: Privacy Policy
          url: /privacy/
          weight: 10
        - name: Imprint
          url: /imprint/
          weight: 15
    header:
      login:
        label: Login
        href: https://my.skribble.com/login
      tryItOut:
        label: Try it out
        href: https://my.skribble.com/signup
    footer:
      navigation:
        titleColumn1: Platform
        titleColumn2: About Skribble
        titleColumn3: Resources
      newsletterTitle: Newsletter
      newsletterText: Electronic signatures and digital trust are hot topics. Stay up to date! See our <a href="/privacy">privacy policy</a>.
