baseurl: /
title: Skribble
params:
  outage: false
disableKinds:
  - taxonomy
  - taxonomyTerm
markup:
  goldmark:
    renderer:
      hardWraps: true
languages:
  de:
    languageName: Deutsch
    flagCode: DE
    weight: 2
    contentDir: content/german
    # phone: +41 44 505 16 64
    outageMsg: Im Moment ist Skribble für einige Benutzer nur eingeschränkt nutzbar. Unser Hosting Anbieter hat schwerwiegende Netzwerksausfälle. Wir arbeiten aktiv an einer Lösung und beobachten die Entwicklung. Updates folgen.
    menu:
      main:
        # Platform dropdown
        - name: Plattform
          url: "/de/features/"
          weight: 5
          identifier: plattform
        - name: Features
          url: "/de/features/"
          weight: 15
          parent: plattform
        - name: Business-Features
          url: "/de/business-features/"
          weight: 20
          parent: plattform
        - name: Integrationen
          url: "/de/integrationen/"
          weight: 25
          parent: plattform
        - name: Identifikation
          url: "/de/identifikation/"
          weight: 30
          parent: plattform
        - name: Beweiskraft erhöhen
          url: "/de/beweiskraft-erhoehen/"
          weight: 35
          parent: plattform
        # Solutions dropdown
        - name: Lösungen
          url: "/de/hr/"
          weight: 15
          identifier: solutions
        - name: HR
          url: "/de/hr/"
          weight: 10
          parent: solutions
        - name: Anwälte
          url: "/de/anwaelte/"
          weight: 15
          parent: solutions
        # Preise
        - name: Preise
          url: "/de/preise/"
          weight: 20
      footer1:
        - name: Features
          url: /de/features/
          weight: 5
        - name: Business-Features
          url: /de/business-features/
          weight: 10
        - name: Integrationen
          url: /de/integrationen/
          weight: 15
        - name: Identifikation
          url: /de/identifikation/
          weight: 20
        - name: Beweiskraft erhöhen
          url: "/de/beweiskraft-erhoehen/"
          weight: 25 
        - name: FES für Business
          url: "/de/identifikation/fes-fuer-business/"
          weight: 30
        - name: QES freischalten
          url: /de/qes-freischalten/
          weight: 35
      footer2:
        - name: HR
          url: /de/hr/
          weight: 5
        - name: Anwälte
          url: /de/anwaelte/
          weight: 10
      footer3:
        - name: Mission
          url: /de/ueber-uns/
          weight: 5
        - name: Team
          url: /de/team/
          weight: 10
        - name: Karriere
          url: /de/karriere/
          weight: 15
        - name: Medien
          url: /de/medien/
          weight: 20
        - name: Partner
          url: /de/partner/
          weight: 25
        - name: Kontakt
          url: "/de/kontakt/"
          weight: 30
      footer4:
        - name: News
          url: https://news.skribble.com
          weight: 5
        - name: Help-Center
          url: https://help.skribble.com/deutsch
          weight: 10
        - name: API-Ressource
          url: https://doc.skribble.com/
          weight: 15
        - name: Signaturstandards
          url: /de/signaturstandards/
          weight: 20
        - name: QES-Validator
          url: /de/qes-validator/
          weight: 25
        - name: Status
          url: /status/
          weight: 30  
      meta:
        - name: Datenschutzbestimmungen
          url: /de/datenschutz/
          weight: 5
        - name: Nutzungsbedingungen
          url: /de/nutzungsbedingungen/
          weight: 10
        - name: AGB
          url: /de/agb/
          weight: 15
        - name: Cookies
          url: /de/cookie-richtlinie/
          weight: 20
        - name: Impressum
          url: /de/impressum/
          weight: 25
      footermobile:
        - name: Datenschutzbestimmungen
          url: /de/datenschutz/
          weight: 5
        - name: Nutzungsbedingungen
          url: /de/nutzungsbedingungen/
          weight: 10
        - name: AGB
          url: /de/agb/
          weight: 15
        - name: Cookies
          url: /de/cookie-richtlinie/
          weight: 20
        - name: Impressum
          url: /de/impressum/
          weight: 25

    header:
      contactSales: 
        label: Sales kontaktieren
        href: https://share.hsforms.com/1gxsCjIJRQhaM4GEcCmL7QQ309ws
      login:
        label: Login
        href: https://my.skribble.com/login?lang=de
      tryItOut:
        label: Jetzt loslegen
        href: https://my.skribble.com/signup?lang=de
      makeAnAppointment:
        label: Sales kontaktieren
        href: https://share.hsforms.com/1gxsCjIJRQhaM4GEcCmL7QQ309ws
    footer:
      leftSlot:
        title: QES freischalten?
        text: Lassen Sie sich identifzieren, um mit maximaler Beweiskraft zu signieren.
        button:
          label: Identifizieren lassen
          href: /de/qes-freischalten/
          target:
      rightSlot:
        title: Fragen zu Skribble?
        text: Erzählen Sie uns von Ihrem Anliegen, wir helfen gerne weiter.
        button:
          label: Kontakt aufnehmen
          href: https://share.hsforms.com/1_O5JpbKXTxKeXoQFnf6Obw309ws
          target: _blank
      navigation:
        titleColumn1: Plattform
        titleColumn2: Lösungen
        titleColumn3: Über uns
        titleColumn4: Ressourcen
      newsletterTitle: Newsletter
      newsletterText: Elektronische Signaturen und digitales Vertrauen sind brandaktuelle Themen. Bleiben Sie auf dem Laufenden! <br class="hide-for-mobile">Unsere <a href="/de/datenschutz">Datenschutzerklärungen</a> anschauen.
  en:
    languageName: English
    flagCode: GB
    weight: 1
    contentDir: content/english
    # phone: +41 44 505 16 64
    outageMsg: Service is currently degraded for certain users of Skribble. Our hosting provider is experiencing a major network outage. We are monitoring the situation and will keep you updated.
    menu:
      main:
        # Platform dropdown
        - name: Platform
          url: "/features/"
          weight: 5
          identifier: platform
        - name: Features
          url: "/features/"
          weight: 15
          parent: platform
        - name: Business features
          url: "/business-features/"
          weight: 20
          parent: platform
        - name: Integrations
          url: "/integrations/"
          weight: 25
          parent: platform
        - name: Identification
          url: "/identification/"
          weight: 30
          parent: platform
        - name: Increase legal weight
          url: "/increase-legal-weight/"
          weight: 35
          parent: platform
        # Solutions dropdown
        - name: Solutions
          url: "/hr/"
          weight: 15
          identifier: solutions
        - name: HR
          url: "/hr/"
          weight: 10
          parent: solutions
        - name: Lawyer
          url: "/Lawyer/"
          weight: 15
          parent: solutions
        # Pricing
        - name: Pricing
          url: "/pricing/"
          weight: 20
      footer1:
        - name: Features
          url: /features/
          weight: 10
        - name: Business features
          url: /business-features/
          weight: 15
        - name: Integrations
          url: /integrations/
          weight: 25
        - name: Identification
          url: /identification/
          weight: 30
        - name: Increase legal weight
          url: /increase-legal-weight/
          weight: 35
        - name: AES for Business
          url: /identification/aes-for-business/
          weight: 40
        - name: Enable QES
          url: /enable-qes/
          weight: 45
      footer2:
        - name: HR
          url: /hr/
          weight: 5
        - name: Lawyer
          url: /lawyer/
          weight: 10
      footer3:
        - name: Mission
          url: /about/
          weight: 5
        - name: Team
          url: /team/
          weight: 10
        - name: Careers
          url: /careers/
          weight: 15
        - name: Press room
          url: /pressroom/
          weight: 20
        - name: Partners
          url: /partners/
          weight: 25
        - name: Contact
          url: "/contact/"
          weight: 30
      footer4:
        - name: News
          url: https://news.skribble.com
          weight: 5
        - name: Help-Center
          url: https://help.skribble.com/english
          weight: 10
        - name: API resource
          url: https://doc.skribble.com/
          weight: 15
        - name: Signature standards
          url: /signaturestandards/
          weight: 20
        - name: QES validator
          url: /qes-validator/
          weight: 25
        - name: Status
          url: /status/
          weight: 30          
      meta:
        - name: Privacy Policy
          url: /privacy/
          weight: 5
        - name: Terms of use
          url: /terms-of-use/
          weight: 5
        - name: GTC
          url: /gtc/
          weight: 10
        - name: Cookies
          url: /cookie-policy/
          weight: 15
        - name: Imprint
          url: /imprint/
          weight: 20
      footermobile:
        - name: Privacy Policy
          url: /privacy/
          weight: 5
        - name: Terms of use
          url: /terms-of-use/
          weight: 10
        - name: GTC
          url: /gtc/
          weight: 15
        - name: Cookies
          url: /cookie-policy/
          weight: 20
        - name: Imprint
          url: /imprint/
          weight: 25

    header:
      contactSales: 
        label: Contact sales
        href: https://share.hsforms.com/1eikgwNSWS9aCXBpqMVvrtQ309ws
      login:
        label: Login
        href: https://my.skribble.com/login
      tryItOut:
        label: Get started
        href: https://my.skribble.com/signup
      makeAnAppointment:
        label: Contact Sales
        href: https://share.hsforms.com/1eikgwNSWS9aCXBpqMVvrtQ309ws
    footer:
      leftSlot:
        title: Enable QES?
        text: Get yourself identified to sign with maximum legal weight.
        button:
          label: Get identified
          href: /enable-qes/
          target:
      rightSlot:
        title: Questions about Skribble?
        text: We will be happy to assist you with your enquiry.
        button:
          label: Get in touch
          href: https://share.hsforms.com/1dmhPMWbMQMWQ_bkUfoU2TQ309ws
          target: _blank
      navigation:
        titleColumn1: Platform
        titleColumn2: Solutions
        titleColumn3: About us
        titleColumn4: Resource
      newsletterTitle: Newsletter
      newsletterText: Electronic signatures and digital trust are hot topics. <br class="hide-for-mobile">Stay up to date! See our <a href="/privacy">privacy policy</a>.
  fr:
    languageName: Français
    flagCode: FR
    weight: 3
    contentDir: content/french
    # phone: +41 44 505 16 64
    outageMsg: Le service de Skribble est actuellement dégradé pour certains clients. Notre Hosting Provider fait face à une majeure panne de réseau . Nous surveillons la situation et vous tiendrons au courant.
    menu:
      main:
        # Platform dropdown
        - name: Platforme
          url: "/fr/fonctionnalites/"
          weight: 5
          identifier: platforme
        - name: Fonctionnalités
          url: "/fr/fonctionnalites/"
          weight: 10
          parent: platforme
        - name: Fonctionnalités affaires
          url: "/fr/fonctionnalites-affaires/"
          weight: 15
          parent: platforme
        - name: Integrations
          url: "/fr/integrations/"
          weight: 20
          parent: platforme
        - name: Identification
          url: "/fr/identification/"
          weight: 25
          parent: platforme
        - name: Augmenter force probante
          url: "/fr/augmenter-force-probante/"
          weight: 30
          parent: platforme
        # Solutions dropdown
        - name: Solutions
          url: "/fr/ressources-humaines/"
          weight: 10
          identifier: solutions
        - name: RH
          url: "/fr/ressources-humaines/"
          weight: 15
          parent: solutions
        - name: Juristes
          url: "/fr/juristes/"
          weight: 20
          parent: solutions
        # Tarifs
        - name: Tarifs
          url: "/fr/tarifs/"
          weight: 25
      footer1:
        - name: Fonctionnalités
          url: /fr/fonctionnalites/
          weight: 5
        - name: Fonctionnalités affaires
          url: /fr/fonctionnalites-affaires/
          weight: 10
        - name: Integrations
          url: /fr/integrations/
          weight: 15
        - name: Identification
          url: /fr/identification/
          weight: 20
        - name: Augmenter force probante
          url: /fr/augmenter-force-probante/
          weight: 25
        - name: SEA pour Business
          url: /fr/identification/sea-pour-business/
          weight: 30
        - name: Débloquez SEQ
          url: /fr/debloquez-seq/
          weight: 35
      footer2:
        - name: RH
          url: /fr/ressources-humaines/
          weight: 5
        - name: Juristes
          url: /fr/juristes/
          weight: 10
      footer3:
        - name: Mission
          url: /fr/mission/
          weight: 5
        - name: Equipe
          url: /fr/equipe/
          weight: 10
        - name: Carrière
          url: /fr/carriere/
          weight: 15
        - name: Médias
          url: /fr/medias/
          weight: 20
        - name: Partenaire
          url: /fr/partenaire/
          weight: 25
        - name: Contact
          url: "/fr/contact/"
          weight: 30
      footer4:
        - name: News
          url: https://news.skribble.com
          weight: 5
        - name: Centre d'assistance
          url: https://help.skribble.com/francais
          weight: 10
        - name: API Ressource
          url: https://doc.skribble.com/
          weight: 15
        - name: Normes de signature
          url: /fr/normessignature/
          weight: 20
        - name: Validateur SEQ
          url: /fr/validateur-seq/
          weight: 25
        - name: Status
          url: /status/
          weight: 30  
      meta:
        - name: Politique de Confidentialité
          url: /fr/politique-de-confidentialite/
          weight: 5
        - name: Conditions d'utilisation
          url: /fr/conditions-dutilisation/
          weight: 10
        - name: CG
          url: /fr/cg/
          weight: 15
        - name: Cookies
          url: /fr/politique-relative-aux-cookies/
          weight: 20
        - name: Impressum
          url: /fr/impressum/
          weight: 25
      footermobile:
        - name: Politique de Confidentialité
          url: /fr/politique-de-confidentialite/
          weight: 5
        - name: Conditions d'utilisation
          url: /fr/conditions-dutilisation/
          weight: 10
        - name: CG
          url: /fr/cg/
          weight: 15
        - name: Cookies
          url: /fr/politique-relative-aux-cookies/
          weight: 20
        - name: Impressum
          url: /fr/impressum/
          weight: 25

    header:
      contactSales: 
        label: Contacter les ventes
        href: https://share.hsforms.com/1JHPHJU3QQz2TlyX14QDdKg309ws
      login:
        label: Login
        href: https://my.skribble.com/login?lang=fr
      tryItOut:
        label: Démarrer
        href: https://my.skribble.com/signup?lang=fr
      makeAnAppointment:
        label: Contacter les ventes
        href: https://share.hsforms.com/1JHPHJU3QQz2TlyX14QDdKg309ws
    footer:
      leftSlot:
        title: Déverrouiller la SEQ?
        text: Laissez-vous identifier pour signer avec une force probante maximale. 
        button:
          label: S'identifier
          href: /fr/debloquez-seq/
          target:
      rightSlot:
        title: Questions sur Skribble?
        text: Faites-nous part de votre demande, nous serons heureux de vous aider.
        button:
          label: Prendre contact
          href: https://share.hsforms.com/1-z4iAJzNRMCcmOt9MeTxmg309ws
          target: _blank
      navigation:
        titleColumn1: Plateforme
        titleColumn2: Les solutions
        titleColumn3: À propos de nous
        titleColumn4: Ressources
      newsletterTitle: Newsletter
      newsletterText: Les signatures électroniques et la confiance numérique sont des sujets d'actualité. Restez au courant ! <br class="hide-for-mobile">Consultez notre <a href="/fr/politique-de-confidentialite/">politique de confidentialité</a>.
