baseurl: /
title: Skribble
languages:
  de:
    languageName: Deutsch
    weight: 2
    contentDir: content/german
    menu:
      main:
        - name: Ãœber uns
          url: /ueber-uns/
          weight: 5
        - name: Identifikation
          url: /identifikation/
          weight: 15
        - name: Team
          url: /team/
          weight: 10
        - name: Kontakt
          url: /kontakt/
          weight: 20
      footer:
        - name: Datenschutzbestimmungen
          url: /de/datenschutz
          weight: 10
        - name: Impressum
          url: /de/impressum
          weight: 15
    header:
      login:
        label: Login
        href: https://my.skribble.com/login?lang=de
      tryItOut:
        label: Jetzt ausprobieren
        href: https://my.skribble.com/signup?lang=de
  en:
    languageName: English
    weight: 1
    contentDir: content/english
    menu:
      main:
        - name: About
          url: /about/
          weight: 5
        - name: Identification
          url: /identification/
          weight: 15
        - name: Team
          url: /team/
          weight: 10
        - name: Contact
          url: /contact/
          weight: 20
      footer:
        - name: Privacy Policy
          url: /privacy/
          weight: 10
        - name: Imprint
          url: /imprint/
          weight: 15
    header:
      login:
        label: Login
        href: https://my.skribble.com/login
      tryItOut:
        label: Try it out
        href: https://my.skribble.com/signup
