baseurl: /
title: Skribble
languages:
  de:
    languageName: Deutsch
    flagCode: DE
    weight: 2
    contentDir: content/german
    phone:
      number: +41 44 505 16 64
      link:
    menu:
      main:
        # Platform dropdown
        - name: Plattform
          url: "#"
          weight: 5
          identifier: plattform
        - name: Angebot
          url: "de/angebot/"
          weight: 10
          parent: plattform
        - name: Features
          url: "de/features/"
          weight: 15
          parent: plattform
        - name: Integrationen
          url: "de/integrationen/"
          weight: 20
          parent: plattform
        - name: Identifikation
          url: "/de/identifikation/"
          weight: 25
          parent: plattform
        - name: Identitätsprüfung
          url: "de/identitaetspruefung/"
          weight: 30
          parent: plattform
        # Solutions dropdown
        - name: Lösungen
          url: "#"
          weight: 15
          identifier: solutions
        - name: HR
          url: "de/hr/"
          weight: 10
          parent: solutions
        - name: Anwälte
          url: "de/anwaelte/"
          weight: 15
          parent: solutions
        - name: Kontakt
          url: "de/kontakt/"
          weight: 20  
      footer1:
        - name: Angebot
          url: /de/angebot/
          weight: 5
        - name: Funktionen
          url: /de/funktionen/
          weight: 10
        - name: Integrationen
          url: /de/integrationen/
          weight: 15
        - name: Identifikation
          url: /de/identifikation/
          weight: 20
        - name: Identitätsprüfung
          url: /de/identitaetspruefung/
          weight: 25
      footer2:
        - name: HR
          url: /de/hr/
          weight: 5
        - name: Anwälte
          url: /de/anwaelte/
          weight: 10
      footer3:
        - name: Mission
          url: /de/ueber-uns/
          weight: 5
        - name: Team
          url: /de/team/
          weight: 10
        - name: Medien
          url: /de/medien/
          weight: 15
      footer4:
        - name: News
          url: https://news.skribble.com
          weight: 5
        - name: Help-Center
          url: https://help.skribble.com/deutsch
          weight: 10
        - name: QES erklärt
          url: /de/qes-erklaert/
          weight: 15
      
      meta:
        - name: Datenschutzbestimmungen
          url: /de/datenschutz
          weight: 10
        - name: Impressum
          url: /de/impressum
          weight: 15
    header:
      login:
        label: Login
        href: https://my.skribble.com/login?lang=de
      tryItOut:
        label: Jetzt ausprobieren
        href: https://my.skribble.com/signup?lang=de
      makeAnAppointment:
        label: Jetzt Termin vereinbaren
        href: https://help.skribble.com/meetings/patrick182/call-mit-skribble
    footer:
      leftSlot:
        title: Identität prüfen?
        text: Hol dir bei Skribble eine E-ID und leg mit dem Signieren los.
        button:
          label: Termin vereinbaren
          href: https://help.skribble.com/meetings/patrick182/identifikation-bei-skribble
      rightSlot:
        title: Demo vereinbaren?
        text: Wir kommen gerne persönlich vorbei um dir Skribble zu zeigen.
        button:
          label:  Telefongespräch vereinbaren
          href: https://help.skribble.com/meetings/patrick182/call-mit-skribble
      navigation:
        titleColumn1: Plattform
        titleColumn2: Lösungen
        titleColumn3: Über uns
        titleColumn4: Ressourcen
      newsletterTitle: Newsletter
      newsletterText: Elektronische Signaturen und digitales Vertrauen sind brandaktuelle Themen. Bleibe auf dem Laufenden! <br class="hide-for-mobile">Siehe unsere <a href="/de/datenschutz">Datenschutzerklärungen</a>.
  en:
    languageName: English
    flagCode: GB
    weight: 1
    contentDir: content/english
    phone:
      number: +41 44 505 16 64
      link:
    menu:
      main:
        # Platform dropdown
        - name: Platform
          url: "#"
          weight: 5
          identifier: platform
        - name: Services
          url: "/Services/"
          weight: 10
          parent: platform
        - name: Features
          url: "features/"
          weight: 15
          parent: platform
        - name: Integrations
          url: "integrations/"
          weight: 20
          parent: platform
        - name: Identification
          url: "/identification/"
          weight: 25
          parent: platform
        - name: Identify
          url: "/identify/"
          weight: 30
          parent: platform
        # Solutions dropdown
        - name: Solutions
          url: "#"
          weight: 15
          identifier: solutions
        - name: HR
          url: "/hr/"
          weight: 10
          parent: solutions
        - name: Lawyer
          url: "/Lawyer/"
          weight: 15
          parent: solutions
        - name: Contact
          url: "/contact/"
          weight: 20     
      footer1:
        - name: Services
          url: /services/
          weight: 5
        - name: Features
          url: /features/
          weight: 10
        - name: Integrations
          url: /integrations/
          weight: 15
        - name: Identification
          url: /identification/
          weight: 20
        - name: Identify
          url: /identify/
          weight: 25
      footer2:
        - name: HR
          url: /hr/
          weight: 5
        - name: Lawyer
          url: /lawyer/
          weight: 10
      footer3:
        - name: Mission
          url: /about/
          weight: 5
        - name: Team
          url: /team/
          weight: 10
        - name: Press room
          url: /pressroom/
          weight: 15
      footer4:
        - name: News
          url: https://news.skribble.com
          weight: 5
        - name: Help-Center
          url: https://help.skribble.com/english
          weight: 10
        - name: QES explained
          url: /qes-explained/
          weight: 15
      meta:
        - name: Privacy Policy
          url: /privacy/
          weight: 10
        - name: Imprint
          url: /imprint/
          weight: 15
      footermobile:
        - name: Impressum
          url: /impressum/
          weight: 5
        - name: Data Protection
          url: /dataprotection/
          weight: 10
    header:
      login:
        label: Login
        href: https://my.skribble.com/login
      tryItOut:
        label: Try it out
        href: https://my.skribble.com/signup
      makeAnAppointment:
        label: Make an appointment
        href: https://help.skribble.com/meetings/patrick182/telephone-consultation-skribble
    footer:
      leftSlot:
        title: Do you want to verify your identity?
        text: We verify your identity so that you can start using your QES signature!
        button:
          label: Schedule appointment
          href: https://help.skribble.com/meetings/patrick182/skribble-id-zurich
      rightSlot:
        title: Do you want to schedule a demo session?
        text: We are pleased to come by to introduce you to Skribble.
        button:
          label: Arrange a call
          href: https://help.skribble.com/meetings/patrick182/telephone-consultation-skribble
      navigation:
        titleColumn1: Platform
        titleColumn2: Solutions
        titleColumn3: About us
        titleColumn4: Resource
      newsletterTitle: Newsletter
      newsletterText: Electronic signatures and digital trust are hot topics. <br class="hide-for-mobile">Stay up to date! See our <a href="/privacy">privacy policy</a>.
  fr:
    languageName: Français
    flagCode: FR
    weight: 3
    contentDir: content/french
    phone:
      number: +41 44 505 16 64
      link:
    menu:
      main:
        # Platform dropdown
        - name: Platform
          url: "#"
          weight: 5
          identifier: platform
        - name: Offre
          url: "/fr/offre/"
          weight: 10
          parent: platform
        - name: Fonctionnalités
          url: "fr/fonctionnalites/"
          weight: 15
          parent: platform
        - name: Integrations
          url: "fr/integrations/"
          weight: 20
          parent: platform
        - name: Identification
          url: "/fr/identification/"
          weight: 25
          parent: platform
        - name: Identifions
          url: "fr/identifions/"
          weight: 30
          parent: platform
        # Solutions dropdown
        - name: Solutions
          url: "#"
          weight: 15
          identifier: solutions
        - name: RH
          url: "fr/ressources-humaines/"
          weight: 10
          parent: solutions
        - name: Juristes
          url: "/fr/juristes/"
          weight: 15
          parent: solutions
        - name: Contact
          url: "/fr/contact/"
          weight: 20     
      footer1:
        - name: Offre
          url: /fr/offre/
          weight: 5
        - name: Fonctionnalités
          url: "fr/fonctionnalites/"
          weight: 10
        - name: Integrations
          url: "fr/integrations/"
          weight: 15
        - name: Identification
          url: /fr/identification/
          weight: 20
        - name: Identifions
          url: /fr/identifions/
          weight: 25
      footer2:
        - name: RH
          url: /fr/ressources-humaines/
          weight: 5
        - name: Juristes
          url: /fr/juristes/
          weight: 10
      footer3:
        - name: Mission
          url: /fr/mission/
          weight: 5
        - name: Equipe
          url: /fr/equipe/
          weight: 10
        - name: Médias
          url: /fr/medias/
          weight: 15
      footer4:
        - name: News
          url: https://news.skribble.com
          weight: 5
        - name: Centre d'assistance
          url: https://help.skribble.com/francais
          weight: 10
        - name: QES expliqué
          url: /fr/qes-explique/
          weight: 15
      meta:
        - name: Politique de Confidentialité
          url: /fr/politique-de-confidentialite
          weight: 10
        - name: Impressum
          url: /fr/impressum
          weight: 15
    header:
      login:
        label: Login
        href: https://my.skribble.com/login?lang=fr
      tryItOut:
        label: Essayer maintenant
        href: https://my.skribble.com/signup?lang=fr
      makeAnAppointment:
        label: Fixer un rendez-vous
        href: https://help.skribble.com/meetings/patrick182/consultation-telephone-skribble
    footer:
      leftSlot:
        title: Vérifier l'identité?
        text: Nous vous identifions afin que vous puissiez utiliser la QES!
        button:
          label: Fixer un rendez-vous
          href: https://help.skribble.com/meetings/patrick182/identification-chez-skribble
      rightSlot:
        title: Organiser une démonstration?
        text: Nous passons volontiers en personne afin de vous présenter Skribble.
        button:
          label: Organiser un appel téléphonique
          href: https://help.skribble.com/meetings/patrick182/consultation-telephone-skribble
      navigation:
        titleColumn1: Plateforme
        titleColumn2: Les solutions
        titleColumn3: À propos de nous
        titleColumn4: Ressources
      newsletterTitle: Newsletter
      newsletterText: Les signatures électroniques et la confiance numérique sont des sujets d'actualité. Restez au courant ! <br class="hide-for-mobile">Consultez notre <a href="/fr/politique-de-confidentialite/">politique de confidentialité</a>.
