baseurl: /
title: Skribble
languages:
  de:
    languageName: Deutsch
    weight: 2
    contentDir: content/german
    menu:
      main:
        - name: Über uns
          url: /de/ueber-uns/
          weight: 5
        - name: Identifikation
          url: /de/identifikation/
          weight: 15
        - name: Kontakt
          url: /de/kontakt/
          weight: 20
      footer1:
        - name: Identifikation
          url: /de/identifikation/
          weight: 15
      footer2:
        - name: Über uns
          url: /de/ueber-uns/
          weight: 5
        - name: Team
          url: /de/team/
          weight: 10
        - name: Kontakt
          url: /de/kontakt/
          weight: 20
      footer3:
        - name: Help-Center
          url: https://help.skribble.com/deutsch
          weight: 5
      footer4:
        - name: Datenschutzbestimmungen
          url: /de/datenschutz
          weight: 10
        - name: Impressum
          url: /de/impressum
          weight: 15
    header:
      login:
        label: Login
        href: https://my.skribble.com/login?lang=de
      tryItOut:
        label: Jetzt ausprobieren
        href: https://my.skribble.com/signup?lang=de
      makeAnAppointment:
        label: Jetzt Termin vereinbaren
        href: https://help.skribble.com/meetings/simon79/beratung-zu-identifikationslsungen
    footer:
      navigation:
        titleColumn1: Plattform
        titleColumn2: Über uns
        titleColumn3: Ressourcen
      newsletterTitle: Newsletter
      newsletterText: Elektronische Signaturen und digitales Vertrauen sind brandaktuelle Themen. Bleibe auf dem Laufenden! Siehe unsere <a href="/de/datenschutz">Datenschutzerklärugen</a>.
  en:
    languageName: English
    weight: 1
    contentDir: content/english
    menu:
      main:
        - name: About
          url: /about/
          weight: 5
        - name: Identification
          url: /identification/
          weight: 15
        - name: Contact
          url: /contact/
          weight: 20
      footer1:
        - name: Identification
          url: /identification/
          weight: 15
      footer2:
        - name: About
          url: /about/
          weight: 5
        - name: Team
          url: /team/
          weight: 10
        - name: Contact
          url: /contact/
          weight: 20
      footer3:
        - name: Help-Center
          url: https://help.skribble.com/english
          weight: 5
      footer4:
        - name: Privacy Policy
          url: /privacy/
          weight: 10
        - name: Imprint
          url: /imprint/
          weight: 15
    header:
      login:
        label: Login
        href: https://my.skribble.com/login
      tryItOut:
        label: Try it out
        href: https://my.skribble.com/signup
      makeAnAppointment:
        label: Make an appointment
        href: https://help.skribble.com/meetings/simon79/learn-about-skribbles-identification-means
    footer:
      navigation:
        titleColumn1: Platform
        titleColumn2: About Skribble
        titleColumn3: Resources
      newsletterTitle: Newsletter
      newsletterText: Electronic signatures and digital trust are hot topics. Stay up to date! See our <a href="/privacy">privacy policy</a>.
  fr:
    languageName: Français
    weight: 3
    contentDir: content/french
    menu:
      main:
        - name: A propos de nous
          url: /de/ueber-uns/
          weight: 5
        - name: Identification
          url: /de/identifikation/
          weight: 15
        - name: Contact
          url: /de/kontakt/
          weight: 20
      footer1:
        - name: Identification
          url: /de/identifikation/
          weight: 15
      footer2:
        - name: A propos de nous
          url: /de/ueber-uns/
          weight: 5
        - name: Equipe
          url: /de/team/
          weight: 10
        - name: Contact
          url: /de/kontakt/
          weight: 20
      footer3:
        - name: Centre d'aide
          url: https://help.skribble.com/deutsch
          weight: 5
      footer4:
        - name: Politique de Confidentialité
          url: /fr/politique-de-confidentialite
          weight: 10
        - name: Empreinte
          url: /fr/empreinte
          weight: 15
    header:
      login:
        label: Connexion
        href: https://my.skribble.com/login?lang=de
      tryItOut:
        label: Essayez-la maintenant
        href: https://my.skribble.com/signup?lang=de
      makeAnAppointment:
        label: Fixer un rendez-vous
        href: https://help.skribble.com/meetings/simon79/conseil
    footer:
      navigation:
        titleColumn1: Plateforme
        titleColumn2: A propos de nous
        titleColumn3: Ressources
      newsletterTitle: Bulletin d'information
      newsletterText: Les signatures électroniques et la confiance numérique sont des sujets d'actualité. Restez au courant ! Voir notre <a href="/fr/politique-de-confidentialite/">Politique de Confidentialité</a>.
