baseurl: /
title: Skribble
params:
  outage: false
disableKinds:
  - taxonomy
  - taxonomyTerm
markup:
  goldmark:
    renderer:
      hardWraps: true
languages:
  de:
    languageName: Deutsch
    flagCode: DE
    weight: 2
    contentDir: content/german
    phone: +41 44 505 16 64
    outageMsg: Im Moment ist Skribble für einige Benutzer nur eingeschränkt nutzbar. Unser Hosting Anbieter hat schwerwiegende Netzwerksausfälle. Wir arbeiten aktiv an einer Lösung und beobachten die Entwicklung. Updates folgen.
    menu:
      main:
        # Platform dropdown
        - name: Plattform
          url: "/de/features/"
          weight: 5
          identifier: plattform
        - name: Features
          url: "/de/features/"
          weight: 15
          parent: plattform
        - name: Business-Features
          url: "/de/business-features/"
          weight: 20
          parent: plattform
        - name: Integrationen
          url: "/de/integrationen/"
          weight: 25
          parent: plattform
        - name: Identifikation
          url: "/de/identifikation/"
          weight: 30
          parent: plattform
        - name: QES freischalten
          url: "/de/qes-freischalten/"
          weight: 35
          parent: plattform
        # Solutions dropdown
        - name: Lösungen
          url: "/de/hr/"
          weight: 15
          identifier: solutions
        - name: HR
          url: "/de/hr/"
          weight: 10
          parent: solutions
        - name: Anwälte
          url: "/de/anwaelte/"
          weight: 15
          parent: solutions
        # Preise
        - name: Preise
          url: "/de/preise/"
          weight: 20
      footer1:
        - name: Features
          url: /de/features/
          weight: 5
        - name: Business-Features
          url: /de/business-features/
          weight: 10
        - name: Integrationen
          url: /de/integrationen/
          weight: 15
        - name: Identifikation
          url: /de/identifikation/
          weight: 20
        - name: QES freischalten
          url: /de/qes-freischalten/
          weight: 25
      footer2:
        - name: HR
          url: /de/hr/
          weight: 5
        - name: Anwälte
          url: /de/anwaelte/
          weight: 10
      footer3:
        - name: Mission
          url: /de/ueber-uns/
          weight: 5
        - name: Team
          url: /de/team/
          weight: 10
        - name: Karriere
          url: /de/karriere/
          weight: 15
        - name: Medien
          url: /de/medien/
          weight: 20
        - name: Kontakt
          url: "/de/kontakt/"
          weight: 25
      footer4:
        - name: News
          url: https://news.skribble.com
          weight: 5
        - name: Help-Center
          url: https://help.skribble.com/deutsch
          weight: 10
        - name: API-Ressource
          url: https://doc.skribble.com/
          weight: 15
        - name: Signaturstandards
          url: /de/signaturstandards/
          weight: 20
        - name: QES-Validator
          url: /de/qes-validator/
          weight: 25
      meta:
        - name: Datenschutzbestimmungen
          url: /de/datenschutz/
          weight: 5
        - name: Nutzungsbedingungen
          url: /de/nutzungsbedingungen/
          weight: 10
        - name: AGB
          url: /de/agb/
          weight: 15
        - name: Impressum
          url: /de/impressum/
          weight: 20
      footermobile:
        - name: Datenschutzbestimmungen
          url: /de/datenschutz/
          weight: 5
        - name: Nutzungsbedingungen
          url: /de/nutzungsbedingungen/
          weight: 10
        - name: AGB
          url: /de/agb/
          weight: 15
        - name: Impressum
          url: /de/impressum/
          weight: 20

    header:
      login:
        label: Login
        href: https://my.skribble.com/login?lang=de
      tryItOut:
        label: Jetzt ausprobieren
        href: https://my.skribble.com/signup?lang=de
      makeAnAppointment:
        label: Jetzt Termin vereinbaren
        href: https://help.skribble.com/meetings/patrick182/call-mit-skribble
    footer:
      leftSlot:
        title: Beweiskraft maximieren?
        text: Lass dich identifzieren und schalte den höchsten E-Signatur-Standard frei.
        button:
          label: Identifizieren lassen
          href: /de/qes-freischalten/
          target:
      rightSlot:
        title: Demo vereinbaren?
        text: Wir kommen gerne persönlich vorbei um dir Skribble zu zeigen.
        button:
          label:  Telefongespräch vereinbaren
          href: https://help.skribble.com/meetings/patrick182/call-mit-skribble
          target: _blank
      navigation:
        titleColumn1: Plattform
        titleColumn2: Lösungen
        titleColumn3: Über uns
        titleColumn4: Ressourcen
      newsletterTitle: Newsletter
      newsletterText: Elektronische Signaturen und digitales Vertrauen sind brandaktuelle Themen. Bleibe auf dem Laufenden! <br class="hide-for-mobile">Siehe unsere <a href="/de/datenschutz">Datenschutzerklärungen</a>.
  en:
    languageName: English
    flagCode: GB
    weight: 1
    contentDir: content/english
    phone: +41 44 505 16 64
    outageMsg: Service is currently degraded for certain users of Skribble. Our hosting provider is experiencing a major network outage. We are monitoring the situation and will keep you updated.
    menu:
      main:
        # Platform dropdown
        - name: Platform
          url: "/features/"
          weight: 5
          identifier: platform
        - name: Features
          url: "/features/"
          weight: 15
          parent: platform
        - name: Business features
          url: "/business-features/"
          weight: 20
          parent: platform
        - name: Integrations
          url: "/integrations/"
          weight: 25
          parent: platform
        - name: Identification
          url: "/identification/"
          weight: 30
          parent: platform
        - name: Enable QES
          url: "/enable-qes/"
          weight: 35
          parent: platform
        # Solutions dropdown
        - name: Solutions
          url: "/hr/"
          weight: 15
          identifier: solutions
        - name: HR
          url: "/hr/"
          weight: 10
          parent: solutions
        - name: Lawyer
          url: "/Lawyer/"
          weight: 15
          parent: solutions
        # Pricing
        - name: Pricing
          url: "/pricing/"
          weight: 20
      footer1:
        - name: Features
          url: /features/
          weight: 10
        - name: Business features
          url: /business-features/
          weight: 15
        - name: Integrations
          url: /integrations/
          weight: 25
        - name: Identification
          url: /identification/
          weight: 30
        - name: Enable QES
          url: /enable-qes/
          weight: 35
      footer2:
        - name: HR
          url: /hr/
          weight: 5
        - name: Lawyer
          url: /lawyer/
          weight: 10
      footer3:
        - name: Mission
          url: /about/
          weight: 5
        - name: Team
          url: /team/
          weight: 10
        - name: Careers
          url: /careers/
          weight: 15
        - name: Press room
          url: /pressroom/
          weight: 20
        - name: Contact
          url: "/contact/"
          weight: 25
      footer4:
        - name: News
          url: https://news.skribble.com
          weight: 5
        - name: Help-Center
          url: https://help.skribble.com/english
          weight: 10
        - name: API resource
          url: https://doc.skribble.com/
          weight: 15
        - name: Signature standards
          url: /signaturestandards/
          weight: 20
        - name: QES validator
          url: /qes-validator/
          weight: 25
      meta:
        - name: Privacy Policy
          url: /privacy/
          weight: 5
        - name: Terms of use
          url: /terms-of-use/
          weight: 5
        - name: GTC
          url: /gtc/
          weight: 10
        - name: Imprint
          url: /imprint/
          weight: 15
      footermobile:
        - name: Privacy Policy
          url: /privacy/
          weight: 5
        - name: Terms of use
          url: /terms-of-use/
          weight: 10
        - name: GTC
          url: /gtc/
          weight: 15
        - name: Imprint
          url: /imprint/
          weight: 20

    header:
      login:
        label: Login
        href: https://my.skribble.com/login
      tryItOut:
        label: Try it now
        href: https://my.skribble.com/signup
      makeAnAppointment:
        label: Make an appointment
        href: https://help.skribble.com/meetings/patrick182/telephone-consultation-skribble
    footer:
      leftSlot:
        title: Want to maximise the legal weight?
        text: Get identified and unlock the highest e-signature standard.
        button:
          label: Get identified
          href: /enable-qes/
          target:
      rightSlot:
        title: Want to schedule a demo session?
        text: We are pleased to come by to introduce you to Skribble.
        button:
          label: Arrange a call
          href: https://help.skribble.com/meetings/patrick182/telephone-consultation-skribble
          target: _blank
      navigation:
        titleColumn1: Platform
        titleColumn2: Solutions
        titleColumn3: About us
        titleColumn4: Resource
      newsletterTitle: Newsletter
      newsletterText: Electronic signatures and digital trust are hot topics. <br class="hide-for-mobile">Stay up to date! See our <a href="/privacy">privacy policy</a>.
  fr:
    languageName: Français
    flagCode: FR
    weight: 3
    contentDir: content/french
    phone: +41 44 505 16 64
    outageMsg: Le service de Skribble est actuellement dégradé pour certains clients. Notre Hosting Provider fait face à une majeure panne de réseau . Nous surveillons la situation et vous tiendrons au courant.
    menu:
      main:
        # Platform dropdown
        - name: Platforme
          url: "/fr/fonctionnalites/"
          weight: 5
          identifier: platforme
        - name: Fonctionnalités
          url: "/fr/fonctionnalites/"
          weight: 10
          parent: platforme
        - name: Fonctionnalités affaires
          url: "/fr/fonctionnalites-affaires/"
          weight: 15
          parent: platforme
        - name: Integrations
          url: "/fr/integrations/"
          weight: 20
          parent: platforme
        - name: Identification
          url: "/fr/identification/"
          weight: 25
          parent: platforme
        - name: Débloquez SEQ
          url: "/fr/debloquez-seq/"
          weight: 30
          parent: platforme
        # Solutions dropdown
        - name: Solutions
          url: "/fr/ressources-humaines/"
          weight: 10
          identifier: solutions
        - name: RH
          url: "/fr/ressources-humaines/"
          weight: 15
          parent: solutions
        - name: Juristes
          url: "/fr/juristes/"
          weight: 20
          parent: solutions
        # Tarifs
        - name: Tarifs
          url: "/fr/tarifs/"
          weight: 25
      footer1:
        - name: Fonctionnalités
          url: "/fr/fonctionnalites/"
          weight: 5
        - name: Fonctionnalités affaires
          url: "/fr/fonctionnalites-affaires/"
          weight: 10
        - name: Integrations
          url: "/fr/integrations/"
          weight: 15
        - name: Identification
          url: /fr/identification/
          weight: 20
        - name: Débloquez SEQ
          url: /fr/debloquez-seq/
          weight: 25
      footer2:
        - name: RH
          url: /fr/ressources-humaines/
          weight: 5
        - name: Juristes
          url: /fr/juristes/
          weight: 10
      footer3:
        - name: Mission
          url: /fr/mission/
          weight: 5
        - name: Equipe
          url: /fr/equipe/
          weight: 10
        - name: Carrière
          url: /fr/carriere/
          weight: 15
        - name: Médias
          url: /fr/medias/
          weight: 20
        - name: Contact
          url: "/fr/contact/"
          weight: 25
      footer4:
        - name: News
          url: https://news.skribble.com
          weight: 5
        - name: Centre d'assistance
          url: https://help.skribble.com/francais
          weight: 10
        - name: API Ressource
          url: https://doc.skribble.com/
          weight: 15
        - name: Normes de signature
          url: /fr/normessignature/
          weight: 20
        - name: Validateur SEQ
          url: /fr/validateur-seq/
          weight: 25

      meta:
        - name: Politique de Confidentialité
          url: /fr/politique-de-confidentialite/
          weight: 5
        - name: Conditions Dutilisation
          url: /fr/conditions-dutilisation/
          weight: 10
        - name: CG
          url: /fr/cg/
          weight: 15
        - name: Impressum
          url: /fr/impressum/
          weight: 20
      footermobile:
        - name: Politique de Confidentialité
          url: /fr/politique-de-confidentialite/
          weight: 5
        - name: Conditions Dutilisation
          url: /fr/conditions-dutilisation/
          weight: 10
        - name: CG
          url: /fr/cg/
          weight: 15
        - name: Impressum
          url: /fr/impressum/
          weight: 20

    header:
      login:
        label: Login
        href: https://my.skribble.com/login?lang=fr
      tryItOut:
        label: Essayer maintenant
        href: https://my.skribble.com/signup?lang=fr
      makeAnAppointment:
        label: Fixer un rendez-vous
        href: https://help.skribble.com/meetings/patrick182/consultation-telephone-skribble
    footer:
      leftSlot:
        title: Maximiser la force probante?
        text: Identifiez-vous et débloquez le standard de signature électronique le plus élevé.
        button:
          label: S'identifier
          href: /fr/debloquez-qes/
          target:
      rightSlot:
        title: Organiser une démonstration?
        text: Nous passons volontiers en personne afin de vous présenter Skribble.
        button:
          label: Organiser un appel téléphonique
          href: https://help.skribble.com/meetings/patrick182/consultation-telephone-skribble
          target: _blank
      navigation:
        titleColumn1: Plateforme
        titleColumn2: Les solutions
        titleColumn3: À propos de nous
        titleColumn4: Ressources
      newsletterTitle: Newsletter
      newsletterText: Les signatures électroniques et la confiance numérique sont des sujets d'actualité. Restez au courant ! <br class="hide-for-mobile">Consultez notre <a href="/fr/politique-de-confidentialite/">politique de confidentialité</a>.
