backend:
  name: git-gateway
media_folder: "site/content/english" # Folder where user uploaded files should go
public_folder: "/"
collections:
  - name: "german"
    label: "Deutsch"
    files:
      - file: "site/content/german/_index.md"
        label: "Home Page"
        name: "home"
        fields:
          - label: "Intro (de)"
            name: "intro"
            widget: "object"
            fields:
              - label: "Title (de)"
                name: "title"
                widget: "string"
              - label: "Text (de)"
                name: "text"
                widget: "markdown"
              - label: "Image (de)"
                name: "image"
                widget: "object"
                fields:
                  - name: "mobile"
                    widget: "object"
                    fields:
                      - name: "filename"
                        widget: "image"
                  - name: "desktop"
                    widget: "object"
                    fields:
                      - name: "filename"
                        widget: "image"
              - label: "Alt text (de)"
                name: "alt_text"
                widget: "string"
              - label: "Link (de)"
                name: "link"
                widget: "object"
                fields:
                  - name: "text"
                    widget: "string"
                  - name: "href"
                    widget: "string"
              - label: "Partner (de)"
                name: "partner"
                widget: "object"
                fields:
                  - name: "image"
                    widget: "image"
                  - name: "text"
                    widget: "string"
                  - name: "alt_text"
                    widget: "string"

  - name: "english"
    label: "English"
    files:
      - file: "site/content/english/_index.md"
        label: "Home Page"
        name: "home"
        fields:
          - label: "Intro"
            name: "intro"
            widget: "object"
            fields:
              - label: "Title"
                name: "title"
                widget: "string"
              - label: "Text"
                name: "text"
                widget: "markdown"
